### ISSUE TITLE
Uninstall features

### ISSUE THREAD

**Issue by leapofazzam123** [Maxython/pacman-for-termux#10]
**Is your feature request related to a problem? Please describe.**
pacman-on-termux always broke my termux.

**Describe the solution you'd like**
I would like an uninstall feature for pacman-on-termux install.sh

**Describe alternatives you've considered**
I opened a failsafe session and removed ../usr

**Comment by Maxython** [comment]
This is rather strange, since everything works for me.  

Are you getting errors after installing pacman or after installing some packages?  

> I would like an uninstall feature for pacman-on-termux install.sh

Such a function will be possible, but it will only be possible if pacman does not have any packages installed. If it already exists, then you can remove pacmam only by removing usr and other system directories.

**Comment by Maxython** [comment]
Closing since it is deprecated
